  USE MASTER 

IF DB_ID('BD_PROYECTO_ACTUALIZADA3') IS NOT NULL 
 BEGIN
   USE MASTER 
    DROP  DATABASE  BD_PROYECTO_ACTUALIZADA3 
  END
   CREATE DATABASE BD_PROYECTO_ACTUALIZADA3
    GO 

	USE BD_PROYECTO_ACTUALIZADA3
	 GO





/*
CREATE TABLE TB_USUARIO
(
COD_USU         INT  IDENTITY(1,1) NOT NULL ,--SE AUTOINCREMENTA
NOMBRE_USU		VARCHAR(50)		NOT NULL,--NOMBRE DE LA PERSONA NATURAL O JURIDICA
APELLIDO_USU	VARCHAR(80)		NOT NULL,--APELLIDOS DEL JUGADOR O NOMBRE COMPLETO DEL REPRESENTANTE LEGAL O DUEÑO DE LA EMPRESA
RUC_USU		VARCHAR(11)		NOT NULL,--DNI DEL JUGADOR O RUC DE EMPRESA
CORREO_USU		VARCHAR(30)		NOT NULL,--CORREO DE CONTACTO
FECH_NAC_USU	VARCHAR(100)	NOT NULL,--NACIMIENTO DEL JUGADOR O FUNDACION DE LA EMPRESA
ID_USU			VARCHAR(20)		NOT NULL,--SOLO EN CASO DE JUGADOR
PASS_USU		VARCHAR(20)		NOT NULL,--SOLO EN CASO DE JUGADOR
PRIMARY KEY (COD_USU)
)
GO*/

CREATE TABLE TB_USUARIO_TIENDA
(
 COD_USU_TIENDA  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
 RAZON_SOCIAL    VARCHAR(100) NOT NULL,  
 REP_LEGAL	 VARCHAR(100) NOT NULL,
 CORREO_UST		 VARCHAR(100) NOT NULL,
 --CONFIRMAR_CORREO VARCHAR(50) NOT NULL,
 DIRECCION		VARCHAR(50) NOT NULL,
 TELEFONO		CHAR(10) NOT NULL,
 FECHA_CONSTITU	DATE NOT NULL,
 RUC			CHAR (11) NOT NULL,
 ID_USU_TIENDA	 VARCHAR(100) NOT NULL,
 CONTRA_USU_TIENDA VARCHAR(30) NOT NULL,

 
)
GO 

CREATE TABLE TB_USUARIO_JUGADOR 
(
 COD_JUGADOR INT IDENTITY (1,1)  NOT NULL PRIMARY KEY,
 NOM_JUGADOR VARCHAR(100) NOT NULL,
 APELLIDO_JUGADOR VARCHAR(100) NOT NULL,
 CORREO_ELECTRONICO  CHAR(50) NOT NULL,
 --COFIRMA_CORREO     VARCHAR(100)NOT NULL,
 ID_USUARIO_JUG		VARCHAR(100) NOT NULL,
 CONTRASEÑA			VARCHAR(100) NOT NULL,
 DIRECCION			VARCHAR(50) NOT NULL, 
 CIUDAD				VARCHAR(50) NOT NULL,
 DNI				CHAR(9) NOT NULL,
 FECHA_NACIMIENTO   DATE    NOT NULL
)
GO
 
CREATE TABLE TB_USUARIO_REGULADOR
(
 COD_REG   INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
 NOM_REG   VARCHAR (100) NOT NULL,  
 APE_REG   VARCHAR (100) NOT NULL,
 CORREO	   CHAR(50) NOT NULL,
 --CONFIRMACION VARCHAR(50) NOT NULL,
 --GRUPO_PER VARCHAR (100) NOT NULL,
 CATEGORIA INT   NOT NULL,
 NIVEL     INT   NOT NULL,  
 COD_ID    CHAR(10) NOT NULL
)
GO 

IF OBJECT_ID('TB_TIPO_USUARIO')IS NOT NULL
	DROP TABLE TB_TIPO_USUARIO
GO
/*
CREATE TABLE TB_TIPO_USUARIO
(
COD_TUSU 	INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
--LOS DOS SIGUIENTES CAMPOS SE AGREGARAN CON UN DISPARADO
--CADA VEZ Q SE INGRESE UN VALOR A LA TABLA TB_USUARIO EL DISPARADOR TOMARA EL DATO  ID_USU Y COLOCARA EL TIPO DE USUARIO POR DEFECTO 1 QUE SIGNIFICA USUARIO JUGADOR
TIPO_USU        INT DEFAULT 1  NOT NULL,
ID_USU       VARCHAR(20) NOT NULL,
--COD_USU      INT       NOT NULL
 )
GO
*/
/*
ALTER TABLE TB_TIPO_USUARIO
ADD CONSTRAINT  PKTIPUSU PRIMARY KEY(COD_TUSU)
GO 
*/
/*
ALTER TABLE TB_TIPO_USUARIO
Add Constraint fkCODUSU Foreign Key (COD_USU) References TB_USUARIO
Go 
*/
/*
ALTER TABLE TB_TIPO_USUARIO
ADD CONSTRAINT  FKIDUSU FOREIGN KEY(ID_USU) REFERENCES TB_USUARIO
GO
*/
/*
ALTER TABLE TB_TIENDA
ADD CONSTRAINT  PKCODTIE PRIMARY KEY(COD_TIE)
GO 
*/
/*
ALTER TABLE TB_TIENDA
ADD CONSTRAINT  FKIDUS FOREIGN KEY(COD_TUSU) REFERENCES TB_TIPO_USUARIO
GO
*/
CREATE TABLE TB_EVENTO
(
COD_EVEN		INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
NOMBRE_EVEN		VARCHAR(100) NOT NULL,
DESC_EVEN		VARCHAR(100) NOT NULL,
INFO			VARCHAR(100) NOT NULL,
FECH_INC_EVEN		VARCHAR(50) NOT NULL,
FECH_FIN_EVEN		VARCHAR(50) NOT NULL,
CIUDAD_EVEN			VARCHAR(20) NOT NULL,
DIRECCION			VARCHAR(20) NOT NULL,
REFERENCIA			VARCHAR(20) NOT NULL,
 CAPACIDAD_LIMT_EVEN     INT NOT NULL,
NOMBRE_PROMOTOR		VARCHAR(50) NOT NULL, 
CANT_ENTRADA		INT  NOT NULL,
PRECIO				MONEY NOT NULL,
MIN_CANT_ORD		INT  NOT NULL,
CANT_DISP			INT  NOT NULL,
MAX_CANT_USU		INT  NOT NULL,
DESC_ENTRADA		VARCHAR(50) NOT NULL,
NOMBRE_EMPRESA		VARCHAR(50) NOT NULL,
RUC_EMPRESA			CHAR(11) NOT NULL, 
NUMB_CUENTA			CHAR(12) NOT NULL,	
BANCO				VARCHAR(50) NOT NULL,
TIPO_MONEDA			CHAR (3) NOT NULL,
NOMBRE_CONTACTO		VARCHAR(50) NOT NULL,
TELF_CONTACTO		VARCHAR(10) NOT NULL,
EMAIL_CONTACTO		VARCHAR(20) NOT NULL,									
DECR_PREMIO_EVENT	VARCHAR(100) NOT NULL,
COD_USU_TIENDA      INT NOT NULL
)
GO 

ALTER TABLE TB_EVENTO
ADD CONSTRAINT  COD_USU_TIENDA FOREIGN KEY(COD_USU_TIENDA) REFERENCES TB_USUARIO_TIENDA
GO

CREATE TABLE TB_USUARIOXEVENTO(
COD_COMPRA INT NOT NULL PRIMARY KEY,
COD_EVEN		INT NOT NULL

)
GO


ALTER TABLE TB_USUARIOXEVENTO
ADD CONSTRAINT  COD_USU_TIENDA2 FOREIGN KEY(COD_USU_TIENDA) REFERENCES TB_USUARIO_TIENDA
GO
ALTER TABLE TB_USUARIOXEVENTO
ADD CONSTRAINT  COD_EVEN FOREIGN KEY(COD_EVEN) REFERENCES TB_EVENTO
GO

CREATE TABLE TB_REGULADORXEVENTO(
COD_SOLICITUD_EVENTO INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
COD_REG				 INT NOT NULL, 
COD_EVEN			 INT NOT NULL,
ESTADO				 INT NOT NULL 
)
GO


ALTER TABLE  TB_REGULADORXEVENTO
ADD CONSTRAINT COD_REG FOREIGN KEY (COD_REG) REFERENCES TB_USUARIO_REGULADOR
GO

ALTER TABLE  TB_REGULADORXEVENTO
ADD CONSTRAINT COD_EVEN FOREIGN KEY (COD_EVEN) REFERENCES TB_EVENTO
GO

CREATE TABLE TB_JUEGO(
COD_JUEGO INT NOT NULL PRIMARY KEY,
NOMBRE_JUEGO VARCHAR(20) NOT NULL
)

CREATE TABLE TB_PUNTUACION(
COD_PUNTUACION INT NOT NULL PRIMARY KEY,
PUNTUACION INT NOT NULL,
COD_JUEGO INT NOT NULL,
COD_JUGADOR INT NOT NULL
)
ALTER TABLE TB_PUNTUACION
ADD CONSTRAINT  COD_JUEGO2 FOREIGN KEY(COD_JUEGO) REFERENCES TB_JUEGO
GO
ALTER TABLE TB_PUNTUACION
ADD CONSTRAINT  COD_JUGADOR FOREIGN KEY(COD_JUGADOR) REFERENCES TB_USUARIO_JUGADOR
GO

/*
ALTER TABLE TB_EVENTO 
ADD CONSTRAINT  PK_COD_EVEN PRIMARY KEY(COD_EVEN) 
GO
*/


CREATE TABLE DETALLE_EVENTO
(
COD_DEVEN	   INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
COD_EVEN		INT 	NOT NULL ,
ID_USU			VARCHAR(20) NOT NULL,
FECH_DE_INCRIP_EVENT    VARCHAR(50) NOT NULL,
LOGRO_OBTENIDO_EVENT	VARCHAR(50) NOT NULL,
PUNTUACION_EVENT        INT  NOT NULL,  -- PENDIENTE
)
GO

/*
ALTER TABLE TB_DETALLE_EVENTO 
ADD CONSTRAINT  PK_COD_DEVEN PRIMARY KEY(COD_DEVEN) 
GO
*/

ALTER TABLE DETALLE_EVENTO
ADD CONSTRAINT  FKCODEVEN3 FOREIGN KEY(COD_EVEN) REFERENCES TB_EVENTO
GO

/*
ALTER TABLE TB_TIENDA
ADD CONSTRAINT  FKCODEVEN2 FOREIGN KEY(COD_EVEN) REFERENCES TB_DETALLE_EVENTO
GO
*/


-- TRIGGER
/*
CREATE TRIGGER TR_TIPOUSU
ON TB_TIPO_USUARIO  
FOR INSERT 
AS 
 BEGIN
  DECLARE @TIPO_USUARIO  INT 
  DECLARE @COD_USU_TIENDA  INT
  DECLARE @COD_JUGADOR	INT 
  DECLARE @COD_REG      INT  
		 SET  @COD_USU_TIENDA  = (SELECT COD_USU_TIENDA FROM  TB_USUARIO_TIENDA)
		 SET  @COD_JUGADOR  =  (SELECT COD_JUGADOR FROM TB_USUARIO_JUGADOR)
		 SET  @COD_REG    = (SELECT COD_REG FROM TB_USUARIO_REGULADOR)
  
  SELECT @TIPO_USUARIO =
    CASE @TIPO_USUARIO 
			WHEN @TIPO_USUARIO = @COD_USU_TIENDA 
				THEN (INSERT INTO TB_TIPO_USUARIO VALUES())
		    WHEN @TIPO_USUARIO  = @COD_JUGADOR 
				THEN (INSERT INTO TB_TIPO_USUARIO VALUES() )
			ELSE @TIPO_USUARIO =  @COD_REG 
			    THEN (INSERT INTO TB_TIPO_USUARIO VALUES())
			END 
 END
 GO 
*/

/*REGISTROS DE DATOS*/
INSERT INTO TB_USUARIO_REGULADOR VALUES('OSCAR','CARRION','ozuma@hotmail.com',2,4,'UR_001')
INSERT INTO TB_USUARIO_REGULADOR VALUES('LUIS','GANDIA','chicharito@hotmail.com',1,1,'UR_003')
INSERT INTO TB_USUARIO_REGULADOR VALUES('JOSE','BARRENZUELA','mya_34@hotmail.com',2,2,'UR_002')
INSERT INTO TB_USUARIO_REGULADOR VALUES('LESLY','AGUILAR','makoto_45@hotmail.com',1,3,'UR_004')

INSERT INTO TB_USUARIO_TIENDA VALUES('Konami','Luis Gangas','luisito@hotmail.com','AV Fernando Diex Canseco 45','123654789','2010/12/8','86745653','KINDARMA','123456')
INSERT INTO TB_USUARIO_TIENDA VALUES('Pokemon','Ricardo Montolivo','richar_45@hotmail.com','AV Andromeda 32','965326435','2012/9/21','96249642','Kirifuda','7890')
INSERT INTO TB_USUARIO_TIENDA VALUES('DBZ','Antonio Candreva','ac_ds43@hotmail.com','AV Caqueta 434','694516324','2013/12/5','32976264','Meatrix','13579')
INSERT INTO TB_USUARIO_TIENDA VALUES('PES','Xabi ALonso','xabi_1@hotmail.com','Plaza Norte 43','937562167','2015/12/15','36423946','Yusaku','24680')

INSERT INTO TB_USUARIO_JUGADOR VALUES('PEDRO','CRISTOBAL','ped_cris_21@hotmail.com','MASTERPOKEMON','masterpokemon','AV. Panama 32','Lima','76893456','1994/8/21')
INSERT INTO TB_USUARIO_JUGADOR VALUES('AUSTIN','FUJIKI','aus_213@hotmail.com','MASTERFIFA','masterfifa','av fontana 21','California','79468234','1997/5/13')
INSERT INTO TB_USUARIO_JUGADOR VALUES('SERENA','KETCHUM','amor_ash_19@hotmail.com','OCTAVAGENERACION','octavageneracion','AV. Andromeda','Paris','77892094','1999/1/5')
INSERT INTO TB_USUARIO_JUGADOR VALUES('AKIZA','FUDO','ak_fu_18@hotmail.com','5ds','5ds','AV. tiahuanaco','Bogota','73298439','2000/3/31')

/*PROCEDURES*/
/*LOGIN*/
IF OBJECT_ID('USP_LOGIN')IS NOT NULL
	DROP PROCEDURE USP_LOGIN
GO

CREATE PROCEDURE USP_LOGIN
@ID_USUARIO VARCHAR(100),
@CONTRASEÑA VARCHAR(30)
AS
select ID_USUARIO_JUG, CONTRASEÑA
from TB_USUARIO_JUGADOR
WHERE
ID_USUARIO_JUG = @ID_USUARIO AND
CONTRASEÑA = @CONTRASEÑA
GO

EXECUTE USP_LOGIN 'MASTERPOKEMON','masterpokemon'
GO

/*USUARIO_REGULADOR*/
IF OBJECT_ID('USP_REGISTRO_USUARIO_REGULADOR')IS NOT NULL
	DROP PROCEDURE USP_REGISTRO_USUARIO_REGULADOR
GO

CREATE PROCEDURE USP_REGISTRO_USUARIO_REGULADOR
@NOMBRE_USU_REG VARCHAR(100),
@APELLIDOS_USU_REG VARCHAR(100),
@CORREO_REG CHAR(50),
@CATEGORIA_REG VARCHAR(100),
@NIVEL_REG VARCHAR(20),
@COD_ID_REG VARCHAR(20)
AS
INSERT INTO TB_USUARIO_REGULADOR VALUES(@NOMBRE_USU_REG,@APELLIDOS_USU_REG,@CORREO_REG,@CATEGORIA_REG,@NIVEL_REG,@COD_ID_REG)
go

execute USP_REGISTRO_USUARIO_REGULADOR 'alex', 'Mandela', 'larrynegro@hotmail.com',1, 2, 'UR_001'
GO


IF OBJECT_ID('USP_LISTAR_USUARIO_REGULADOR')IS NOT NULL
	DROP PROCEDURE USP_LISTAR_USUARIO_REGULADOR
GO

CREATE PROCEDURE USP_LISTAR_USUARIO_REGULADOR
AS
SELECT * FROM TB_USUARIO_REGULADOR
GO

EXECUTE USP_LISTAR_USUARIO_REGULADOR
GO


IF OBJECT_ID('USP_ACTUALIZAR_USUARIO_REGULADOR')IS NOT NULL
	DROP PROCEDURE USP_ACTUALIZAR_USUARIO_REGULADOR
GO

CREATE PROCEDURE USP_ACTUALIZAR_USUARIO_REGULADOR
@COD_USU_REG INT,
@CATEGORIA INT,
@NIVEL INT
AS
UPDATE TB_USUARIO_REGULADOR
SET CATEGORIA = @CATEGORIA,
NIVEL = @NIVEL
WHERE
COD_REG = @COD_USU_REG
GO

EXECUTE USP_ACTUALIZAR_USUARIO_REGULADOR 1, 1,3
GO


IF OBJECT_ID('USP_ELIMINAR_USUARIO_REGULADOR')IS NOT NULL
	DROP PROCEDURE USP_ELIMINAR_USUARIO_REGULADOR
GO

CREATE PROCEDURE USP_ELIMINAR_USUARIO_REGULADOR
@COD_USU_REG INT
AS
DELETE FROM TB_USUARIO_REGULADOR
WHERE 
COD_REG = @COD_USU_REG
GO

EXECUTE USP_ELIMINAR_USUARIO_REGULADOR 5
GO

/*USUARIO_JUGADOR*/
IF OBJECT_ID('USP_REGISTRO_USUARIO_JUGADOR')IS NOT NULL
	DROP PROCEDURE USP_REGISTRO_USUARIO_JUGADOR
GO

CREATE PROCEDURE USP_REGISTRO_USUARIO_JUGADOR
@NOMBRE_USU_JUGADOR VARCHAR(100),
@APELLIDO_USU_JUGADOR VARCHAR(100),
@CORREO_USU_JUGADOR VARCHAR(50),
@ID_USUARIO_JUGADOR VARCHAR(100),
@CONTRASEÑA_USU_JUGADOR VARCHAR(30),
@DIRECCION VARCHAR(50),
@CIUDAD VARCHAR(50),
@DNI CHAR(9),
@FECHA_NACI_USU_JUGADOR DATE
AS
INSERT INTO TB_USUARIO_JUGADOR VALUES(@NOMBRE_USU_JUGADOR,@APELLIDO_USU_JUGADOR,@CORREO_USU_JUGADOR,@ID_USUARIO_JUGADOR,@CONTRASEÑA_USU_JUGADOR,@DIRECCION,@CIUDAD,@DNI,@FECHA_NACI_USU_JUGADOR)
go

execute USP_REGISTRO_USUARIO_JUGADOR 'BRYAN', 'Hazard', 'bry_haz@hotmail.com','admin','admmin', 'AV Andromeda 323','Lima', '74682834','1996/01/28'
GO


IF OBJECT_ID('USP_LISTAR_USUARIO_JUGADOR')IS NOT NULL
	DROP PROCEDURE USP_LISTAR_USUARIO_JUGADOR
GO

CREATE PROCEDURE USP_LISTAR_USUARIO_JUGADOR
AS
SELECT * FROM TB_USUARIO_JUGADOR
GO

EXECUTE USP_LISTAR_USUARIO_JUGADOR
GO


IF OBJECT_ID('USP_ACTUALIZAR_USUARIO_JUGADOR')IS NOT NULL
	DROP PROCEDURE USP_ACTUALIZAR_USUARIO_JUGADOR
GO

CREATE PROCEDURE USP_ACTUALIZAR_USUARIO_JUGADOR
@COD_USU_JUG INT,
@CORREO_USU_JUG VARCHAR(50),
@DIRECCION VARCHAR(50),
@CIUDAD VARCHAR(50)
AS
UPDATE TB_USUARIO_JUGADOR
SET CORREO_ELECTRONICO = @CORREO_USU_JUG,
DIRECCION = @DIRECCION,
CIUDAD = @CIUDAD
WHERE
COD_JUGADOR = @COD_USU_JUG
GO

EXECUTE USP_ACTUALIZAR_USUARIO_JUGADOR 6, 'eden_hazard@hotmail.com', 'Av tiahuanco 32', 'Munich'
GO


IF OBJECT_ID('USP_ELIMINAR_USUARIO_JUGADOR')IS NOT NULL
	DROP PROCEDURE USP_ELIMINAR_USUARIO_JUGADOR
GO

CREATE PROCEDURE USP_ELIMINAR_USUARIO_JUGADOR
@COD_USU_JUG INT
AS
DELETE FROM TB_USUARIO_JUGADOR
WHERE 
COD_JUGADOR = @COD_USU_JUG
GO

EXECUTE USP_ELIMINAR_USUARIO_JUGADOR 7
GO

/*USUARIO TIENDA*/
IF OBJECT_ID('USP_REGISTRO_USUARIO_TIENDA')IS NOT NULL
	DROP PROCEDURE USP_REGISTRO_USUARIO_TIENDA
GO

CREATE PROCEDURE USP_REGISTRO_USUARIO_TIENDA
@RAZON_SOCIAL VARCHAR(100),
@REPRESENTANTE VARCHAR(100),
@CORREO_ELECTRONICO VARCHAR(100),
@DIRECCION VARCHAR(50),
@TELEFONO CHAR(10),
@FECHA_CONSTI DATE,
@RUC CHAR(11),
@ID_USU_TIENDA VARCHAR(100),
@CONTRASEÑA_TIENDA VARCHAR(30)
AS
INSERT INTO TB_USUARIO_TIENDA VALUES(@RAZON_SOCIAL,@REPRESENTANTE,@CORREO_ELECTRONICO,@DIRECCION,@TELEFONO,@FECHA_CONSTI,@RUC,@ID_USU_TIENDA,@CONTRASEÑA_TIENDA)
go

execute USP_REGISTRO_USUARIO_TIENDA 'Megaman', 'Gustavo Rodriguez', 'larry_papi@hotmail.com','Av yusaku','994375932', '2017/11/24','54353534', 'ASTRO','astro'
GO


IF OBJECT_ID('USP_LISTAR_USUARIO_TIENDA')IS NOT NULL
	DROP PROCEDURE USP_LISTAR_USUARIO_TIENDA
GO

CREATE PROCEDURE USP_LISTAR_USUARIO_TIENDA
AS
SELECT * FROM TB_USUARIO_TIENDA
GO

EXECUTE USP_LISTAR_USUARIO_TIENDA
GO


IF OBJECT_ID('USP_ACTUALIZAR_USUARIO_TIENDA')IS NOT NULL
	DROP PROCEDURE USP_ACTUALIZAR_USUARIO_TIENDA
GO

CREATE PROCEDURE USP_ACTUALIZAR_USUARIO_TIENDA
@COD_USU_TIENDA INT,
@REPRESENTANTE VARCHAR(100),
@CORREO_ELECTRONICO VARCHAR(100),
@DIRECCION VARCHAR(50),
@TELEFONO CHAR(10)
AS
UPDATE TB_USUARIO_TIENDA
SET REP_LEGAL = @REPRESENTANTE,
CORREO_UST = @CORREO_ELECTRONICO,
DIRECCION = @DIRECCION,
TELEFONO = @TELEFONO
WHERE
COD_USU_TIENDA = @COD_USU_TIENDA
GO

EXECUTE USP_ACTUALIZAR_USUARIO_TIENDA 1, 'Pedro Ojeda', 'yuyasakaki@hotmail.com', 'av la molina','999444222'
GO


IF OBJECT_ID('USP_ELIMINAR_USUARIO_TIENDA')IS NOT NULL
	DROP PROCEDURE USP_ELIMINAR_USUARIO_TIENDA
GO

CREATE PROCEDURE USP_ELIMINAR_USUARIO_TIENDA
@COD_USU_TIENDA INT
AS
DELETE FROM TB_USUARIO_TIENDA
WHERE 
COD_USU_TIENDA = @COD_USU_TIENDA
GO

EXECUTE USP_ELIMINAR_USUARIO_TIENDA 7
GO